/*
	SDbgExt2 - Copyright (C) 2013, Steve Niemitz

    SDbgExt2 is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SDbgExt2 is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SDbgExt2.  If not, see <http://www.gnu.org/licenses/>.
*/

typedef struct AppDomainAndValue
{
	CLRDATA_ADDRESS Domain;
	CLRDATA_ADDRESS Value;
	BOOL IsInitialized;
} AppDomainAndValue;


typedef struct ClrThreadContext
{
	CLRDATA_ADDRESS ExecutionContext;
	CLRDATA_ADDRESS IllogicalCallContext;
	CLRDATA_ADDRESS LogicalCallContext;
	CLRDATA_ADDRESS HostContext;
} ClrThreadContext;

typedef enum ClrDateTimeKind { KIND_UNSPECIFIED, KIND_UTC, KIND_LOCAL } ClrDateTimeKind;

typedef struct ClrDateTime
{
	ULONG64 Ticks;
	ClrDateTimeKind Kind;
	
	UINT Year;
	UINT Month;
	UINT Day;
	
	UINT Hour;
	UINT Minute;
	UINT Second;
	UINT Millisecond;
} ClrDateTime;

typedef struct ClrHttpContext
{
	ClrDateTime RequestStartTime; 
	[string] BSTR RequestUrl;
	[string] BSTR QueryString;
} ClrHttpContext;

typedef struct ClrDelegateInfo
{
	CLRDATA_ADDRESS Target;
	CLRDATA_ADDRESS MethodDesc;
} ClrDelegateInfo;