/*
	SDbgExt2 - Copyright (C) 2013, Steve Niemitz

    SDbgExt2 is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    SDbgExt2 is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SDbgExt2.  If not, see <http://www.gnu.org/licenses/>.
*/

import "oaidl.idl";
import "ocidl.idl";
import "ClrData.idl";

import "idl\_IXCLRDataProcess3.idl";
import "idl\_IClrProcess.idl";
import "idl\_IClrObject.idl";
import "idl\_ISDbgExt.idl";

[
	uuid(D90CA04C-0A5E-4E81-9F53-83EFB19B3EAD)
]
library SDbgCore
{
	interface IClrObjectArray;
	interface IClrObject;
	interface IDacMemoryAccess;
	interface IXCLRDataProcess3;
	interface IClrProcess;
	interface ISDbgExt;

	interface IEnumHashtableBatchCallback;
	interface IEnumObjectsBatchCallback;
	interface IEnumFieldsCallback;
	interface IDbgHelper;
	interface ISDbgBootstrapper;
	enum CorElementType;
}