import "oaidl.idl";
import "ocidl.idl";
import "ClrData.idl";

import "idl\_IXCLRDataProcess3.idl";
import "idl\_IClrProcess.idl";
import "idl\_IClrObject.idl";
//import "idl\_ISDbgExt.idl";

[
	uuid(D90CA04C-0A5E-4E81-9F53-83EFB19B3EAD)
]
library SDbgCore
{
	interface IClrObjectArray;
	interface IDacMemoryAccess;
	interface IXCLRDataProcess3;

	interface IEnumThreadsCallback;
	interface IEnumObjectsCallback;

	struct AppDomainAndValue;
	struct ClrThreadContext;

	interface IClrProcess;
	//interface ISDbgExt;
	enum CorElementType;
}