@echo off
echo Creating DLL...
tlbimp SDbgCore.tlb /machine:agnostic

echo ILDASMing...
ildasm SDbgCore.dll /out=SDbgCore.il

echo Do your thing...
pause

echo Reassembling...
ilasm /dll SDbgCore.il /output=SDbgCore.dll